config:
  base:
    endpoint: http://localhost:8090/producto

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/proyecto_carrito

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka