spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/proyecto_productos
  application:
    name: microservicio-producto

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka