spring:
  cloud:
    gateway:
      routes[0]:
        id: microservicio-producto
        uri: lb://microservicio-producto
        predicates: Path=/api/producto/**
        filters: StripPrefix=2
      routes[1]:
        id: microservicio-usuario
        uri: lb://microservicio-usuario
        predicates: Path=/api/usuario/**
        filters: StripPrefix=2
      routes[2]:
        id: microservicio-carrito-compras
        uri: lb://microservicio-carrito-compras
        predicates: Path=/api/carrito/**
        filters: StripPrefix=2
      routes[3]:
        id: microservicio-ordenes-pagos
        uri: lb://microservicio-ordenes-pagos
        predicates: Path=/api/orden/**
        filters: StripPrefix=2
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
