server:
  port: 8095

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/proyecto_facturacion
  cloud:
    function:
      definition: notificacionfacturacion
    stream:
      kafka:
        default:
          consumer:
            configuration:
              max.poll.interval.ms: 240000
        binder:
          brokers: "localhost:9092"
      bindings:
        notificacionfacturacion-in-0:
          destination: proyecto_topic
          consumer:
            concurrency: 1
          group: $Default
  mail:
    host: smtp.gmail.com
    port: 587
    username: correo.proyecto.bootcamp@gmail.com
    password: swasosjdngipffay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 2000