config:
  base:
    endpoint:
      usuario: http://microservicio-usuario/usuario
      carrito: http://microservicio-carrito-compras/carrito
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/proyecto_orden
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
      bindings:
        topic:
          destination: proyecto_topic
          producer:
            requiredGroups: $Default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka